// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeTunnel.Data;

#nullable disable

namespace SafeTunnel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523050223_AgregarSignalRYAtaques")]
    partial class AgregarSignalRYAtaques
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeTunnel.Models.Simulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertaAtaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AtaqueSimulado")
                        .HasColumnType("bit");

                    b.Property<string>("CalidadConexion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CifradoRSA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashRecibido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuellaRSA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IntegridadValida")
                        .HasColumnType("bit");

                    b.Property<string>("IpDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpVPN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatenciaAtaqueMs")
                        .HasColumnType("int");

                    b.Property<int?>("LatenciaMs")
                        .HasColumnType("int");

                    b.Property<string>("MensajeInterceptado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeProcesado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaquetesPerdidos")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Retransmisiones")
                        .HasColumnType("int");

                    b.Property<string>("Riesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAtaqueEjecutado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("SafeTunnel.Models.TransmisionVpn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashIntegridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpProtegidaSimulada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpRealSimulada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeCifrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeDescifrado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensajeOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelSeguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransmisionesVpn");
                });

            modelBuilder.Entity("SafeTunnel.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
